CC=arm-unknown-linux-gnu-gcc

all:
	$(CC) -lm -o lab2 lab2.c \
		-L /opt/arm-unknown-linux-gnu/arm-unknown-linux-gnu/lib/ \
		-I /opt/arm-unknown-linux-gnu/arm-unknown-linux-gnu/include/ \
		-I /home/kuolun/microtime/linux/include/
clean:
	rm lab2
